apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2020-04-20T08:38:42Z"
  labels:
    app: grafana
  name: grafana-test
  namespace: grafana
secrets:
- name: grafana-test-token-klstg
