apiVersion: v1
data:
  admin-password: V3doWHVRQndkZldCRWNLSThzUEx5R0xLcE4xV2pjV3RXZmR2dEVQRw==
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: grafana
type: Opaque
